language: python
python: 2.7
env:
  - PLONE_VERSION=4.2 QA=true
  - PLONE_VERSION=4.3
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install: make install
script: make tests
after_success: make qa
notifications:
  irc: irc.freenode.org#simplesconsultoria
