language: python
python: 2.7
env:
  - PLONE_VERSION=4.2 QA=true
  - PLONE_VERSION=4.3
matrix:
  allow_failures:
    - python: 2.7
      env: PLONE_VERSION=4.3
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - make install
script: make tests
after_success: make qa
notifications:
  irc: irc.freenode.org#simplesconsultoria
