language: python
python: 2.7
env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3 QA=true
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - test "$PLONE_VERSION" = "4.2" && sed -ie "s#plone.app.layout = 2.3.10#plone.app.layout = 2.2.13#" travis.cfg || true
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -N -q
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bin/test && bin/code-analysis
after_success:
  - test -v QA && bin/coverage.sh && pip install -q coveralls && coveralls || true
after_failure:
  - bin/buildout annotate -c travis.cfg
  - firefox -v
notifications:
  irc: irc.freenode.org#simplesconsultoria
