language: python
python: 2.7
env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3 QA=true
  - PLONE_VERSION=5.0
matrix:
  allow_failures:
    - env: PLONE_VERSION=5.0
  fast_finish: true
install:
  - cp travis-$PLONE_VERSION.cfg travis.cfg
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg annotate
  - bin/buildout -c travis.cfg -N -q
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bin/code-analysis && bin/test
after_success:
  - test $QA && bin/coverage.sh && pip install -q coveralls && coveralls || true
after_failure:
  - firefox -v
notifications:
  irc: irc.freenode.org#simplesconsultoria
