language: python
python: "2.7"
before_install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
install:
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -N -q -t 3
script: bin/test
