language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
addons:
  firefox: 45.8.0esr
env:
- PLONE_VERSION=4.2
- PLONE_VERSION=4.3
install:
- sed -ie "s#test-4.3.x.cfg#test-$PLONE_VERSION.x.cfg#" buildout.cfg
- test $PLONE_VERSION = 4.2 && sed -i "/\[versions\]/a collective.js.jqueryui = 1.8.16.9" buildout.cfg || true
- test $PLONE_VERSION = 4.2 && sed -ie "s#test-eggs =#test-eggs = collective.syndication#" buildout.cfg || true
- python bootstrap.py
- bin/buildout annotate
- bin/buildout -Nq
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage
- pip install -q coveralls
- coveralls
after_script:
# Firefox complains: GConf-WARNING **: Got Disconnected from DBus.
# And then it keeps hanging, causing a failed job after 30-50 minutes.
# So we just kill Firefox.
- pkill -9 firefox
notifications:
  irc: irc.freenode.org#simplesconsultoria
