language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
env:
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
matrix:
  allow_failures:
    - env: PLONE_VERSION=5.0
  fast_finish: true
install:
- sed -ie "s#test-4.3.x.cfg#test-$PLONE_VERSION.x.cfg#" buildout.cfg
- sed -ie "s#versions-4.3.x.cfg#versions-$PLONE_VERSION.x.cfg#" buildout.cfg
- python bootstrap.py
- bin/buildout annotate
- bin/buildout -Nq
before_script:
- export DISPLAY=:99.0
- export GROK_DISABLE_TEMPLATE_WARNING=on
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage -t "--layer=!Robot"
- pip install -q coveralls
- coveralls
notifications:
  irc: irc.freenode.org#simplesconsultoria
