language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
  - parts/node
env:
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
matrix:
  fast_finish: true
install:
- sed -ie "s#test-4.3#test-$PLONE_VERSION#" buildout.cfg
- sed -ie "s#versions-4.3#versions-$PLONE_VERSION#" buildout.cfg
- python bootstrap.py
- bin/buildout annotate
- bin/buildout -Nq
before_script:
- export DISPLAY=:99.0
- export GROK_DISABLE_TEMPLATE_WARNING=on
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
- bin/code-analysis
- test $PLONE_VERSION == 5.0 && bin/test --layer=!Robot || bin/test
after_success:
- bin/createcoverage -t "--layer=!Robot"
- pip install -q coveralls
- coveralls
notifications:
  irc: irc.freenode.org#simplesconsultoria
